[package]
name = "yaks-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
slint = "1.12"
tokio.workspace = true
yaks-common.path = "../yaks-common"
yaks-core.path = "../yaks-core"

[build-dependencies]
slint-build = "1.12"

