import { HorizontalBox } from "std-widgets.slint";


export component Row inherits HorizontalLayout {
    height: 25px;
    spacing: 5px;
}

export component RightAlignedRow inherits Row {
    Rectangle {
        horizontal-stretch: 1;
        height: 0;
    }
    @children
}

export component Center inherits HorizontalLayout {
    Rectangle {
        horizontal-stretch: 1;
        height: 0;
    }
    @children
    Rectangle {
        horizontal-stretch: 1;
        height: 0;
    }
}

