import { LineEdit, HorizontalBox, Button, VerticalBox, ProgressIndicator, ComboBox, SpinBox, Spinner, CheckBox } from "std-widgets.slint";
import { Input, Jobs, Range, Process, Downloader } from "component.slint";


export component MainWindow inherits Window {
    title: "YAKS";
    callback download(link: string, out: string, format: string, from: string, to: string, workers: int, );
    // main layout
    VerticalBox {
        padding-top: 35px;
        spacing: 10px;
        // url input
        Input {
            desc: "Artist:";
            link := LineEdit {
                placeholder-text: "Also accepts the format {platform}/{user_id} (e.g. fanbox/123456)";
            }

            jobs := Jobs { }

            Button {
                text: "Download";
                width: 80px;
                clicked => {
                    root.download(
                        link.text,
                        out.text,
                        format.text,
                        range.max,
                        range.min,
                        jobs.value,
                    )
                }
            }
        }
        // save path
        Input {
            desc: "Save to:";
            out := LineEdit {
                placeholder-text: "Parent folder";
            }

            Button {
                text: "Browse...";
            }

            Text {
                text: "/";
                vertical-alignment: center;
                font-size: 18px;
            }

            format := LineEdit {
                placeholder-text: "Use '/' to create sub-folders";
            }
        }
        // filters (range and so on)
        Input {
            desc: "Filter:";
            Rectangle {
                horizontal-stretch: 1;
            }

            range := Range { }
        }
        // general process
        Process {
            name: "Collecting Files";
            progress: 50%;
        }
        // progress bars
        VerticalBox {
            spacing: 0;
            Downloader {
                left-text: "Total: " + self.cur + "/" + self.total + " (and more)";
                right-text: "1.45 MiB/s";
                cur: 13;
                total: 80;
            }

            Downloader {
                left-text: "123456_1.webp";
                right-text: "545 KiB/s";
                cur: 54;
                total: 100;
            }
        }
    }
}
