[package]
name = "yaks-common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
flate2.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
